# docker build -t mbrella:latest .
# docker run -p 5000:5000 mbrella:latest
FROM python:2.7

# Create app directory
WORKDIR /usr/src/app

# Add code
ADD . .

# Install the dependencies
RUN pip install -r requirements.txt
# Set environment variables
ENV FLASK_APP=src/main.py
ENV FLASK_ENV=development
# Expose the application's port
EXPOSE 5000

# Run the application
#  py.test test/test.py --log-cli-level=10 -s
CMD ["py.test", "test/test.py", "--log-cli-level=10", "-s"]
#CMD ["flask", "run", "--host=0.0.0.0", "--port=5000"]